home:
    path:  /
    defaults: { _controller: mooclineCompteBundle:Register:index }

inscription_Enseignant:
    path:  /inscription-enseignant
    defaults: { _controller: mooclineCompteBundle:Register:inscriptionEnseignant }

inscription_Etudiant:
    path:  /inscription-etudiant
    defaults: { _controller: mooclineCompteBundle:Register:inscrEtudiant }
