home:
    path:  /
    defaults: { _controller: mooclineCompteBundle:Registration:index }

# admin path
#admin_registration:
#    path:  /admin/registration
#    defaults: { _controller: mooclineCompteBundle:Admin:adminRegister }

admin_send_invitation:
    path:  /admin/send-invitation/{email}
    defaults: { _controller: mooclineCompteBundle:Admin:sendInvitation }


# Registration path
inscription_Enseignant:
    path:  /inscription-enseignant
    defaults: { _controller: mooclineCompteBundle:Admin:adminRegister }

inscription_Etudiant:
    path:  /inscription-etudiant
    defaults: { _controller: mooclineCompteBundle:Registration:inscrEtudiant }

modification_Etudiant:
    path:     /modificationEtudiant/{id}
    defaults: { _controller: mooclineCompteBundle:Modification:modificationEtu }

modification_Enseignant:
    path:     /modificationEnseignant/{id}
    defaults: { _controller: mooclineCompteBundle:Modification:modificationEns }

vue_Etudiant:
    path:     /vueEtudiant/{id}
    defaults: { _controller: mooclineCompteBundle:Modification:voirEtu }
    requirements:
        _method:  GET
        id: \d+

vue_Enseignant:
    path:     /vueEnseignant/{id}
    defaults: { _controller: mooclineCompteBundle:Modification:voirEns }

dashboard_Admin:
    path:  /admin/dashboard/{id}
    defaults: { _controller: mooclineCompteBundle:Dashboard:DashboardAdmin }

dashboard_Etudiant:
    path:  /dashboard/{id}
    defaults: { _controller: mooclineCompteBundle:Dashboard:DashboardEtu }
   
dashboard_Enseignant:
    path:  /dashboardEns/{id}
    defaults: { _controller: mooclineCompteBundle:Dashboard:dashboardEns }

# Contact path
contact_particulier:
    path:  /contact
    defaults: { _controller: mooclineCompteBundle:Contact:contactParticulier}

contact_ecole_partenaire:
    path:  /ecole-partenaire
    defaults: { _controller: mooclineCompteBundle:Contact:contactEcole}
    
qui_sommes_nous:
    path:  /qui-sommes-nous
    defaults: { _controller: mooclineCompteBundle:Contact:qsNous}
