mooc_exo_homepage:
    pattern:  /
    defaults: { _controller: mooclineExoBundle:Default:index }

mooc_exo_cree:
    pattern:  /cree
    defaults: { _controller: mooclineExoBundle:Default:creeExo }

mooc_exo_ajouter:
    pattern:  /ajouter
    defaults: { _controller: mooclineExoBundle:Default:ajouter }
