parameters:
#    moocline_forum.example.class: moocline\ForumBundle\Example

services:
#    moocline_forum.example:
#        class: %moocline_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
