parameters:
#    moocline_cours.example.class: moocline\CoursBundle\Example

services:
#    moocline_cours.example:
#        class: %moocline_cours.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
