<?php

namespace moocline\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends EntityRepository
{

	public function findExByIdOfFExJoinedToFEx($id)
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT ex, feuille FROM mooclineExoBundle:Exercice ex
				JOIN ex.feuilleEx feuille
				WHERE feuille.id = :id'
			)->setParameter('id', $id);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

}
