<?php

namespace moocline\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeuilleExRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeuilleExRepository extends EntityRepository
{
	public function findFeuillesExByIdOfCoursJoinedToCours($id)
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT feuille, c FROM mooclineExoBundle:Feuille feuille
				JOIN feuille.cours c
				WHERE c.id = :id'
			)->setParameter('id', $id);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}