<?php

namespace moocline\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PRepository extends EntityRepository
{
}
