<?php

namespace moocline\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QCMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

	public function findQuestByIdOfExJoinedToEx($id)
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT quest, ex FROM mooclineExoBundle:Question quest
				JOIN quest.exercice ex
				WHERE ex.id = :id'
			)->setParameter('id', $id);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

}
