<?php

namespace moocline\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends EntityRepository
{

public function findRepByIdOfQuestJoinedToQuest($id)
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT rep, quest FROM mooclineExoBundle:Reponse rep
				JOIN rep.question quest
				WHERE quest.id = :id'
			)->setParameter('id', $id);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}

}
