<?php

namespace moocline\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeuilleExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeuilleExerciceRepository extends EntityRepository
{
}
