parameters:
#    mooc_exo.example.class: moocline\ExoBundle\Example

services:
#    mooc_exo.example:
#        class: %mooc_exo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
