parameters:
#    moocline_authentification.example.class: Moocline\AuthentificationBundle\Example

services:
#    moocline_authentification.example:
#        class: %moocline_authentification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
