<?php

namespace moocline\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactEcoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactEcoleRepository extends EntityRepository
{
}
